//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "Campaigns")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub save_data_id: i64,
    #[sea_orm(column_type = "Text")]
    pub campaign_name_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chapters::Entity")]
    Chapters,
    #[sea_orm(
        belongs_to = "super::save_datas::Entity",
        from = "Column::SaveDataId",
        to = "super::save_datas::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SaveDatas,
}

impl Related<super::chapters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chapters.def()
    }
}

impl Related<super::save_datas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaveDatas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
