//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "ChapterSideTypes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chapter_sides::Entity")]
    ChapterSides,
}

impl Related<super::chapter_sides::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChapterSides.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
