//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "ChapterSides")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub chapter_sid: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub side_id: String,
    pub berries_available: i64,
    pub berries_collected: i64,
    pub goldenstrawberry_achieved: i64,
    pub goldenwingstrawberry_achieved: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chapter_side_rooms::Entity")]
    ChapterSideRooms,
    #[sea_orm(
        belongs_to = "super::chapter_side_types::Entity",
        from = "Column::SideId",
        to = "super::chapter_side_types::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChapterSideTypes,
    #[sea_orm(
        belongs_to = "super::chapters::Entity",
        from = "Column::ChapterSid",
        to = "super::chapters::Column::Sid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Chapters,
    #[sea_orm(has_many = "super::game_sessions::Entity")]
    GameSessions,
}

impl Related<super::chapter_side_rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChapterSideRooms.def()
    }
}

impl Related<super::chapter_side_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChapterSideTypes.def()
    }
}

impl Related<super::chapters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chapters.def()
    }
}

impl Related<super::game_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
