//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "GameSessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub chapter_sid: String,
    #[sea_orm(column_type = "Text")]
    pub side_id: String,
    #[sea_orm(column_type = "Text")]
    pub date_time_start: String,
    pub duration_ms: i64,
    pub is_goldenberry_attempt: i64,
    pub is_goldenberry_completed: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chapter_sides::Entity",
        from = "(Column::ChapterSid, Column::SideId)",
        to = "(super::chapter_sides::Column::ChapterSid, super::chapter_sides::Column::SideId)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChapterSides,
    #[sea_orm(
        belongs_to = "super::chapters::Entity",
        from = "Column::ChapterSid",
        to = "super::chapters::Column::Sid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Chapters,
    #[sea_orm(has_many = "super::game_session_chapter_room_stats::Entity")]
    GameSessionChapterRoomStats,
}

impl Related<super::chapter_sides::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChapterSides.def()
    }
}

impl Related<super::chapters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chapters.def()
    }
}

impl Related<super::game_session_chapter_room_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameSessionChapterRoomStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
