//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "GameSessionChapterRoomStats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub gamesession_id: String,
    #[sea_orm(column_type = "Text")]
    pub chapter_sid: String,
    #[sea_orm(column_type = "Text")]
    pub side_id: String,
    #[sea_orm(column_type = "Text")]
    pub room_name: String,
    pub deaths_in_room: i64,
    pub dashes_in_room: i64,
    pub strawberries_achieved_in_room: i64,
    pub hearts_achieved_in_room: i64,
    pub jumps_in_room: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chapter_side_rooms::Entity",
        from = "(Column::ChapterSid, Column::SideId, Column::RoomName)",
        to = "(super::chapter_side_rooms::Column::ChapterSid, super::chapter_side_rooms::Column::SideId, super::chapter_side_rooms::Column::Name)",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChapterSideRooms,
    #[sea_orm(
        belongs_to = "super::game_sessions::Entity",
        from = "Column::GamesessionId",
        to = "super::game_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GameSessions,
}

impl Related<super::chapter_side_rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChapterSideRooms.def()
    }
}

impl Related<super::game_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
