//! TheCelesteTracker: `SeaORM` Entity and Database connections (manual added), @generated by sea-orm-codegen 2.0

#![allow(unused_imports)]
pub mod prelude;

pub mod campaigns;
pub mod chapter_side_rooms;
pub mod chapter_side_types;
pub mod chapter_sides;
pub mod chapters;
pub mod game_session_chapter_room_stats;
pub mod game_sessions;
pub mod save_datas;
pub mod users;


use sea_orm::{Database, DatabaseConnection, DbErr};
use std::{env, sync::OnceLock};

pub static DB_CONNECTION: OnceLock<DatabaseConnection> = OnceLock::new();

#[macro_export]
macro_rules! DB {
    () => {
        $crate::db::DB_CONNECTION
            .get()
            .expect("Database connection not initialized")
    };
}

pub async fn init_connection(database_url: String) -> Result<(), DbErr> {
    let db = Database::connect(database_url).await?;
    DB_CONNECTION.set(db).ok();
    Ok(())
}

pub async fn close_connection() -> Result<(), DbErr> {
    if let Some(conn) = DB_CONNECTION.get() {
        conn.clone().close().await?;
    }
    Ok(())
}