//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "Users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::save_datas::Entity")]
    SaveDatas,
}

impl Related<super::save_datas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SaveDatas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
