pub mod db;
pub mod commands;

use crate::db::init_connection;


#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub async fn run() {
    let db_path = String::from(
        "sqlite://C:/Users/Kristan/Desktop/TheCelesteTracker_MOD_DB_TEST_AUTOGENERATED.db",
    );
    let _ = init_connection(db_path).await.expect("Error initializing the database");

    let builder = tauri::Builder::default()
        .plugin(tauri_plugin_opener::init());

    commands::register(builder)
        .run(tauri::generate_context!())
        .expect("error while running tauri application");

}
