// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2, arg3);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function GetAssetAsBase64(arg1) {
  return window['go']['main']['App']['GetAssetAsBase64'](arg1);
}

export function GetAvailableCampaigns(arg1) {
  return window['go']['main']['App']['GetAvailableCampaigns'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function GetCollectionCampaignIDs(arg1) {
  return window['go']['main']['App']['GetCollectionCampaignIDs'](arg1);
}

export function GetCollectionStats(arg1, arg2) {
  return window['go']['main']['App']['GetCollectionStats'](arg1, arg2);
}

export function GetCollections(arg1) {
  return window['go']['main']['App']['GetCollections'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MaximiseApp() {
  return window['go']['main']['App']['MaximiseApp']();
}

export function Query_GetGlobalStats(arg1, arg2) {
  return window['go']['main']['App']['Query_GetGlobalStats'](arg1, arg2);
}

export function Query_GetRecentHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Query_GetRecentHistory'](arg1, arg2, arg3, arg4);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function UpdateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2, arg3);
}
