// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MaximiseApp() {
  return window['go']['main']['App']['MaximiseApp']();
}

export function Query_GetGlobalStats(arg1, arg2) {
  return window['go']['main']['App']['Query_GetGlobalStats'](arg1, arg2);
}

export function Query_GetRecentHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Query_GetRecentHistory'](arg1, arg2, arg3, arg4);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}
