// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {src} from '../models';

export function CreateCampaign(arg1:number,arg2:string,arg3:any,arg4:any):Promise<number>;

export function CreateCollection(arg1:number,arg2:string,arg3:Array<number>):Promise<number>;

export function CreateLobby(arg1:number,arg2:string,arg3:any,arg4:any):Promise<number>;

export function DeleteCampaign(arg1:number):Promise<void>;

export function DeleteCollection(arg1:number):Promise<void>;

export function GetAssetAsBase64(arg1:string):Promise<string>;

export function GetAvailableCampaigns(arg1:number):Promise<Array<src.CampaignItem>>;

export function GetCampaign(arg1:number):Promise<src.Campaign>;

export function GetCampaigns(arg1:number):Promise<Array<src.Campaign>>;

export function GetCollection(arg1:number):Promise<src.Collection>;

export function GetCollectionCampaignIDs(arg1:number):Promise<Array<number>>;

export function GetCollectionStats(arg1:Array<number>,arg2:any):Promise<Array<src.LevelCollectionStats>>;

export function GetCollections(arg1:number):Promise<Array<src.Collection>>;

export function GetIndexedAssetAsBase64(arg1:string):Promise<string>;

export function GetLobbies(arg1:number):Promise<Array<src.Lobby>>;

export function Greet(arg1:string):Promise<string>;

export function IndexModAssets():Promise<src.ModAssetIndexResult>;

export function MaximiseApp():Promise<void>;

export function Query_GetGlobalStats(arg1:number,arg2:number):Promise<Array<src.GlobalStats>>;

export function Query_GetRecentHistory(arg1:number,arg2:number,arg3:number,arg4:number):Promise<Array<src.RecentRun>>;

export function QuitApp():Promise<void>;

export function UpdateCampaign(arg1:number,arg2:string,arg3:any,arg4:any):Promise<void>;

export function UpdateCollection(arg1:number,arg2:string,arg3:Array<number>):Promise<void>;
