use thecelestetracker_desktop_lib as App;
use App::db::init_connection;
use App::commands::db::general_info::get_general_info;
use App::commands::db::save_slots::get_save_slots;
use sea_orm::ConnectionTrait;

#[tokio::main]
async fn main() {
    let db_path = String::from(
        "sqlite://C:/Users/Kristan/Desktop/TheCelesteTracker_MOD_DB_TEST_AUTOGENERATED.db",
    );
    let _ = init_connection(db_path)
        .await
        .expect("Error initializing the database");

    // Add missing column if it doesn't exist (ignore error if it already exists)
    let db = App::DB!();
    let _ = db.execute_unprepared(
        "ALTER TABLE ChapterSides ADD COLUMN heart_collected INTEGER DEFAULT 0;"
    ).await;

    // Test save slots
    let slots = get_save_slots(1).await.expect("Error fetching save slots");
    println!("Available save slots: {:?}", slots);

    // Test general info for first slot (if available, else default to 1)
    let slot = slots.first().copied().unwrap_or(1);
    let info = get_general_info(1, slot).await.expect("Error fetching general info");
    println!("General Info for slot {}: {:#?}", slot, info);
}
